package cn.com.cscec8b.bm.subcntrtransfer.model.queries;

import cn.com.cscec8b.framework.model.common.CustomEntityImpl;
import cn.com.cscec8b.framework.model.common.CustomViewRowImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 03 18:52:45 CST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmSubcntrTransferHeaderTVORowImpl extends CustomViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ProjectId {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getProjectId();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setProjectId((Number)value);
            }
        }
        ,
        CntrName {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getCntrName();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setCntrName((String)value);
            }
        }
        ,
        BmDocumentType {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getBmDocumentType();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setBmDocumentType((String)value);
            }
        }
        ,
        BmDocumentNumber {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getBmDocumentNumber();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setBmDocumentNumber((String)value);
            }
        }
        ,
        CurrentBmAmount {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getCurrentBmAmount();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setCurrentBmAmount((Number)value);
            }
        }
        ,
        TransferDate {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getTransferDate();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setTransferDate((Date)value);
            }
        }
        ,
        VendorName {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getVendorName();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setVendorName((String)value);
            }
        }
        ,
        TransferFromDate {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getTransferFromDate();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setTransferFromDate((Date)value);
            }
        }
        ,
        TransferToDate {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getTransferToDate();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setTransferToDate((Date)value);
            }
        }
        ,
        BmDocumentId {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getBmDocumentId();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setBmDocumentId((Number)value);
            }
        }
        ,
        DocumentNumber {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getDocumentNumber();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setDocumentNumber((String)value);
            }
        }
        ,
        ErpDocumentNumber {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getErpDocumentNumber();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setErpDocumentNumber((String)value);
            }
        }
        ,
        ErpDocumentType {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getErpDocumentType();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setErpDocumentType((String)value);
            }
        }
        ,
        SubcntrId {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getSubcntrId();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setSubcntrId((Number)value);
            }
        }
        ,
        CntrNumber {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getCntrNumber();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setCntrNumber((String)value);
            }
        }
        ,
        TransferAmount {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getTransferAmount();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setTransferAmount((Number)value);
            }
        }
        ,
        TransferErrorMsg {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getTransferErrorMsg();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setTransferErrorMsg((String)value);
            }
        }
        ,
        TransferStatus {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getTransferStatus();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setTransferStatus((String)value);
            }
        }
        ,
        TransferType {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getTransferType();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setTransferType((String)value);
            }
        }
        ,
        Description {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        KeyDocumentNumber {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getKeyDocumentNumber();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setKeyDocumentNumber((String)value);
            }
        }
        ,
        BmGroupId {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getBmGroupId();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setBmGroupId((Number)value);
            }
        }
        ,
        SumCurrentBmAmount {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getSumCurrentBmAmount();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setSumCurrentBmAmount((Number)value);
            }
        }
        ,
        SumTransferAmount {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getSumTransferAmount();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setSumTransferAmount((Number)value);
            }
        }
        ,
        BmSubcntrCustomersLovVO1 {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getBmSubcntrCustomersLovVO1();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TransferStatusLookupLovVO1 {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getTransferStatusLookupLovVO1();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ErpTypeLookupLovVO1 {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getErpTypeLookupLovVO1();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BmTransferTypeLookupLovVO1 {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getBmTransferTypeLookupLovVO1();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StmConfirmedSubCntrLovVO1 {
            public Object get(BmSubcntrTransferHeaderTVORowImpl obj) {
                return obj.getStmConfirmedSubCntrLovVO1();
            }

            public void put(BmSubcntrTransferHeaderTVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BmSubcntrTransferHeaderTVORowImpl object);

        public abstract void put(BmSubcntrTransferHeaderTVORowImpl object,
                                 Object value);

        public int index() {
            return cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.firstIndex() + cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PROJECTID = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.ProjectId.index();
    public static final int CNTRNAME = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.CntrName.index();
    public static final int BMDOCUMENTTYPE = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.BmDocumentType.index();
    public static final int BMDOCUMENTNUMBER = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.BmDocumentNumber.index();
    public static final int CURRENTBMAMOUNT = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.CurrentBmAmount.index();
    public static final int TRANSFERDATE = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.TransferDate.index();
    public static final int VENDORNAME = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.VendorName.index();
    public static final int TRANSFERFROMDATE = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.TransferFromDate.index();
    public static final int TRANSFERTODATE = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.TransferToDate.index();
    public static final int BMDOCUMENTID = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.BmDocumentId.index();
    public static final int DOCUMENTNUMBER = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.DocumentNumber.index();
    public static final int ERPDOCUMENTNUMBER = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.ErpDocumentNumber.index();
    public static final int ERPDOCUMENTTYPE = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.ErpDocumentType.index();
    public static final int SUBCNTRID = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.SubcntrId.index();
    public static final int CNTRNUMBER = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.CntrNumber.index();
    public static final int TRANSFERAMOUNT = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.TransferAmount.index();
    public static final int TRANSFERERRORMSG = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.TransferErrorMsg.index();
    public static final int TRANSFERSTATUS = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.TransferStatus.index();
    public static final int TRANSFERTYPE = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.TransferType.index();
    public static final int DESCRIPTION = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.Description.index();
    public static final int KEYDOCUMENTNUMBER = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.KeyDocumentNumber.index();
    public static final int BMGROUPID = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.BmGroupId.index();
    public static final int SUMCURRENTBMAMOUNT = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.SumCurrentBmAmount.index();
    public static final int SUMTRANSFERAMOUNT = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.SumTransferAmount.index();
    public static final int BMSUBCNTRCUSTOMERSLOVVO1 = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.BmSubcntrCustomersLovVO1.index();
    public static final int TRANSFERSTATUSLOOKUPLOVVO1 = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.TransferStatusLookupLovVO1.index();
    public static final int ERPTYPELOOKUPLOVVO1 = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.ErpTypeLookupLovVO1.index();
    public static final int BMTRANSFERTYPELOOKUPLOVVO1 = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.BmTransferTypeLookupLovVO1.index();
    public static final int STMCONFIRMEDSUBCNTRLOVVO1 = cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.StmConfirmedSubCntrLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BmSubcntrTransferHeaderTVORowImpl() {
    }

    /**
     * Gets BmSubcntrTransferHeaderTEO entity object.
     * @return the BmSubcntrTransferHeaderTEO
     */
    public CustomEntityImpl getBmSubcntrTransferHeaderTEO() {
        return (CustomEntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for the calculated attribute ProjectId.
     * @return the ProjectId
     */
    public Number getProjectId() {
        return (Number) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProjectId.
     * @param value value to set the  ProjectId
     */
    public void setProjectId(Number value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrName.
     * @return the CntrName
     */
    public String getCntrName() {
        return (String) getAttributeInternal(CNTRNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrName.
     * @param value value to set the  CntrName
     */
    public void setCntrName(String value) {
        setAttributeInternal(CNTRNAME, value);
    }

    /**
     * Gets the attribute value for BM_DOCUMENT_TYPE using the alias name BmDocumentType.
     * @return the BM_DOCUMENT_TYPE
     */
    public String getBmDocumentType() {
        return (String) getAttributeInternal(BMDOCUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BM_DOCUMENT_TYPE using the alias name BmDocumentType.
     * @param value value to set the BM_DOCUMENT_TYPE
     */
    public void setBmDocumentType(String value) {
        setAttributeInternal(BMDOCUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BmDocumentNumber.
     * @return the BmDocumentNumber
     */
    public String getBmDocumentNumber() {
        return (String) getAttributeInternal(BMDOCUMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BmDocumentNumber.
     * @param value value to set the  BmDocumentNumber
     */
    public void setBmDocumentNumber(String value) {
        setAttributeInternal(BMDOCUMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentBmAmount.
     * @return the CurrentBmAmount
     */
    public Number getCurrentBmAmount() {
        return (Number) getAttributeInternal(CURRENTBMAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentBmAmount.
     * @param value value to set the  CurrentBmAmount
     */
    public void setCurrentBmAmount(Number value) {
        setAttributeInternal(CURRENTBMAMOUNT, value);
    }

    /**
     * Gets the attribute value for TRANSFER_DATE using the alias name TransferDate.
     * @return the TRANSFER_DATE
     */
    public Date getTransferDate() {
        return (Date) getAttributeInternal(TRANSFERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFER_DATE using the alias name TransferDate.
     * @param value value to set the TRANSFER_DATE
     */
    public void setTransferDate(Date value) {
        setAttributeInternal(TRANSFERDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VendorName.
     * @return the VendorName
     */
    public String getVendorName() {
        return (String) getAttributeInternal(VENDORNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VendorName.
     * @param value value to set the  VendorName
     */
    public void setVendorName(String value) {
        setAttributeInternal(VENDORNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransferFromDate.
     * @return the TransferFromDate
     */
    public Date getTransferFromDate() {
        return (Date) getAttributeInternal(TRANSFERFROMDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransferFromDate.
     * @param value value to set the  TransferFromDate
     */
    public void setTransferFromDate(Date value) {
        setAttributeInternal(TRANSFERFROMDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransferToDate.
     * @return the TransferToDate
     */
    public Date getTransferToDate() {
        return (Date) getAttributeInternal(TRANSFERTODATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransferToDate.
     * @param value value to set the  TransferToDate
     */
    public void setTransferToDate(Date value) {
        setAttributeInternal(TRANSFERTODATE, value);
    }

    /**
     * Gets the attribute value for BM_DOCUMENT_ID using the alias name BmDocumentId.
     * @return the BM_DOCUMENT_ID
     */
    public Number getBmDocumentId() {
        return (Number) getAttributeInternal(BMDOCUMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for BM_DOCUMENT_ID using the alias name BmDocumentId.
     * @param value value to set the BM_DOCUMENT_ID
     */
    public void setBmDocumentId(Number value) {
        setAttributeInternal(BMDOCUMENTID, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
     * @return the DOCUMENT_NUMBER
     */
    public String getDocumentNumber() {
        return (String) getAttributeInternal(DOCUMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_NUMBER using the alias name DocumentNumber.
     * @param value value to set the DOCUMENT_NUMBER
     */
    public void setDocumentNumber(String value) {
        setAttributeInternal(DOCUMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for ERP_DOCUMENT_NUMBER using the alias name ErpDocumentNumber.
     * @return the ERP_DOCUMENT_NUMBER
     */
    public String getErpDocumentNumber() {
        return (String) getAttributeInternal(ERPDOCUMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for ERP_DOCUMENT_NUMBER using the alias name ErpDocumentNumber.
     * @param value value to set the ERP_DOCUMENT_NUMBER
     */
    public void setErpDocumentNumber(String value) {
        setAttributeInternal(ERPDOCUMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for ERP_DOCUMENT_TYPE using the alias name ErpDocumentType.
     * @return the ERP_DOCUMENT_TYPE
     */
    public String getErpDocumentType() {
        return (String) getAttributeInternal(ERPDOCUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ERP_DOCUMENT_TYPE using the alias name ErpDocumentType.
     * @param value value to set the ERP_DOCUMENT_TYPE
     */
    public void setErpDocumentType(String value) {
        setAttributeInternal(ERPDOCUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for SUBCNTR_ID using the alias name SubcntrId.
     * @return the SUBCNTR_ID
     */
    public Number getSubcntrId() {
        return (Number) getAttributeInternal(SUBCNTRID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBCNTR_ID using the alias name SubcntrId.
     * @param value value to set the SUBCNTR_ID
     */
    public void setSubcntrId(Number value) {
        setAttributeInternal(SUBCNTRID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CntrNumber.
     * @return the CntrNumber
     */
    public String getCntrNumber() {
        return (String) getAttributeInternal(CNTRNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CntrNumber.
     * @param value value to set the  CntrNumber
     */
    public void setCntrNumber(String value) {
        setAttributeInternal(CNTRNUMBER, value);
    }

    /**
     * Gets the attribute value for TRANSFER_AMOUNT using the alias name TransferAmount.
     * @return the TRANSFER_AMOUNT
     */
    public Number getTransferAmount() {
        return (Number) getAttributeInternal(TRANSFERAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFER_AMOUNT using the alias name TransferAmount.
     * @param value value to set the TRANSFER_AMOUNT
     */
    public void setTransferAmount(Number value) {
        setAttributeInternal(TRANSFERAMOUNT, value);
    }

    /**
     * Gets the attribute value for TRANSFER_ERROR_MSG using the alias name TransferErrorMsg.
     * @return the TRANSFER_ERROR_MSG
     */
    public String getTransferErrorMsg() {
        return (String) getAttributeInternal(TRANSFERERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFER_ERROR_MSG using the alias name TransferErrorMsg.
     * @param value value to set the TRANSFER_ERROR_MSG
     */
    public void setTransferErrorMsg(String value) {
        setAttributeInternal(TRANSFERERRORMSG, value);
    }

    /**
     * Gets the attribute value for TRANSFER_STATUS using the alias name TransferStatus.
     * @return the TRANSFER_STATUS
     */
    public String getTransferStatus() {
        return (String) getAttributeInternal(TRANSFERSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFER_STATUS using the alias name TransferStatus.
     * @param value value to set the TRANSFER_STATUS
     */
    public void setTransferStatus(String value) {
        setAttributeInternal(TRANSFERSTATUS, value);
    }

    /**
     * Gets the attribute value for TRANSFER_TYPE using the alias name TransferType.
     * @return the TRANSFER_TYPE
     */
    public String getTransferType() {
        return (String) getAttributeInternal(TRANSFERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFER_TYPE using the alias name TransferType.
     * @param value value to set the TRANSFER_TYPE
     */
    public void setTransferType(String value) {
        setAttributeInternal(TRANSFERTYPE, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for KEY_DOCUMENT_NUMBER using the alias name KeyDocumentNumber.
     * @return the KEY_DOCUMENT_NUMBER
     */
    public String getKeyDocumentNumber() {
        return (String) getAttributeInternal(KEYDOCUMENTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for KEY_DOCUMENT_NUMBER using the alias name KeyDocumentNumber.
     * @param value value to set the KEY_DOCUMENT_NUMBER
     */
    public void setKeyDocumentNumber(String value) {
        setAttributeInternal(KEYDOCUMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for BM_GROUP_ID using the alias name BmGroupId.
     * @return the BM_GROUP_ID
     */
    public Number getBmGroupId() {
        return (Number) getAttributeInternal(BMGROUPID);
    }

    /**
     * Sets <code>value</code> as attribute value for BM_GROUP_ID using the alias name BmGroupId.
     * @param value value to set the BM_GROUP_ID
     */
    public void setBmGroupId(Number value) {
        setAttributeInternal(BMGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumCurrentBmAmount.
     * @return the SumCurrentBmAmount
     */
    public Number getSumCurrentBmAmount() {
        return ((BmSubcntrTransferHeaderTVOImpl)getViewObject()).getSumCurrentBmAmount();

     //   return (Number) getAttributeInternal(SUMCURRENTBMAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumCurrentBmAmount.
     * @param value value to set the  SumCurrentBmAmount
     */
    public void setSumCurrentBmAmount(Number value) {
        setAttributeInternal(SUMCURRENTBMAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumTransferAmount.
     * @return the SumTransferAmount
     */
    public Number getSumTransferAmount() {
        return ((BmSubcntrTransferHeaderTVOImpl)getViewObject()).getSumTransferAmount();

     //   return (Number) getAttributeInternal(SUMTRANSFERAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumTransferAmount.
     * @param value value to set the  SumTransferAmount
     */
    public void setSumTransferAmount(Number value) {
        setAttributeInternal(SUMTRANSFERAMOUNT, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BmSubcntrCustomersLovVO1.
     */
    public RowSet getBmSubcntrCustomersLovVO1() {
        return (RowSet)getAttributeInternal(BMSUBCNTRCUSTOMERSLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TransferStatusLookupLovVO1.
     */
    public RowSet getTransferStatusLookupLovVO1() {
        return (RowSet)getAttributeInternal(TRANSFERSTATUSLOOKUPLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ErpTypeLookupLovVO1.
     */
    public RowSet getErpTypeLookupLovVO1() {
        return (RowSet)getAttributeInternal(ERPTYPELOOKUPLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BmTransferTypeLookupLovVO1.
     */
    public RowSet getBmTransferTypeLookupLovVO1() {
        return (RowSet)getAttributeInternal(BMTRANSFERTYPELOOKUPLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StmConfirmedSubCntrLovVO1.
     */
    public RowSet getStmConfirmedSubCntrLovVO1() {
        return (RowSet)getAttributeInternal(STMCONFIRMEDSUBCNTRLOVVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.firstIndex()) && (index < cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.count())) {
            return cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.staticValues()[index - cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.firstIndex()) && (index < cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.count())) {
            cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.staticValues()[index - cn.com.cscec8b.bm.subcntrtransfer.model.queries.BmSubcntrTransferHeaderTVORowImpl.AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
