package cn.com.cscec8b.bm.subcntrtransfer.model.services.client;

import cn.com.cscec8b.bm.subcntrtransfer.model.services.common.BmSubCntrTransferTaskflowAM;

import java.sql.Connection;

import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 06 15:26:45 CST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BmSubCntrTransferTaskflowAMClient extends ApplicationModuleImpl implements BmSubCntrTransferTaskflowAM {
    /**
     * This is the default constructor (do not remove).
     */
    public BmSubCntrTransferTaskflowAMClient() {
    }


    public String transfer(Number subcntrId, Number auditAmount,
                           Number deductionAmount, Number visaAmount,
                           Date transferDate, Number createBy) {
        Object _ret =
            this.riInvokeExportedMethod(this,"transfer",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Date","oracle.jbo.domain.Number"},new Object[] {subcntrId, auditAmount, deductionAmount, visaAmount, transferDate, createBy});
        return (String)_ret;
    }

    public String isValidateTransferDate(Date transferDate, int orgId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"isValidateTransferDate",new String [] {"oracle.jbo.domain.Date","int"},new Object[] {transferDate, new Integer(orgId)});
        return (String)_ret;
    }

    public String getCurrentUser() {
        Object _ret = this.riInvokeExportedMethod(this,"getCurrentUser",null,null);
        return (String)_ret;
    }

    public String getCurrentProjectNum() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentProjectNum",null,null);
        return (String)_ret;
    }

    public String getCurrentProjectName() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentProjectName",null,null);
        return (String)_ret;
    }

    public Number getCurrentProjectId() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentProjectId",null,null);
        return (Number)_ret;
    }

    public String getCurrentOrganizationName() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentOrganizationName",null,null);
        return (String)_ret;
    }

    public Number getCurrentOrganizationId() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentOrganizationId",null,null);
        return (Number)_ret;
    }

    public Number getCurrentOrgId() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentOrgId",null,null);
        return (Number)_ret;
    }

    public String getCurrentEmployeeName() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentEmployeeName",null,null);
        return (String)_ret;
    }

    public Number getCurrentEmployeeId() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentEmployeeId",null,null);
        return (Number)_ret;
    }

    public Connection getCurrentDBConnection() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentDBConnection",null,null);
        return (Connection)_ret;
    }

    public Double getActualTransferAmount(Number subcntrId,
                                          String documentNumber, String type) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getActualTransferAmount",new String [] {"oracle.jbo.domain.Number","java.lang.String","java.lang.String"},new Object[] {subcntrId, documentNumber, type});
        return (Double)_ret;
    }

    public String generateBMDocumentNumber(String p0, String p1) {
        Object _ret =
            this.riInvokeExportedMethod(this,"generateBMDocumentNumber",new String [] {"java.lang.String","java.lang.String"},new Object[] {p0, p1});
        return (String)_ret;
    }

    public List<String> callStoreProcedure(String p0, List p1, int p2) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callStoreProcedure",new String [] {"java.lang.String","java.util.List","int"},new Object[] {p0, p1, new Integer(p2)});
        return (List<String>)_ret;
    }

    public Number getInvalidTransferStatus(int subcntrId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getInvalidTransferStatus",new String [] {"int"},new Object[] {new Integer(subcntrId)});
        return (Number)_ret;
    }

    public void updateHeaderStatus(String documentNumber, String bmDocumentId,
                                   String bmDocumentType, String status) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateHeaderStatus",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {documentNumber, bmDocumentId, bmDocumentType, status});
        return;
    }

    public String updateTransferHeaderStatus(String documentNumer,
                                             String status) {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateTransferHeaderStatus",new String [] {"java.lang.String","java.lang.String"},new Object[] {documentNumer, status});
        return (String)_ret;
    }
}
