package cn.com.cscec8b.bm.subcntrtransfer.model.services.common;

import java.sql.Connection;

import java.util.List;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 06 15:26:45 CST 2017
// ---------------------------------------------------------------------
public interface BmSubCntrTransferTaskflowAM extends ApplicationModule {
    String transfer(Number subcntrId, Number auditAmount,
                    Number deductionAmount, Number visaAmount,
                    Date transferDate, Number createBy);

    String isValidateTransferDate(Date transferDate, int orgId);

    String getCurrentUser();

    String getCurrentProjectNum();

    String getCurrentProjectName();

    Number getCurrentProjectId();

    String getCurrentOrganizationName();

    Number getCurrentOrganizationId();

    Number getCurrentOrgId();

    String getCurrentEmployeeName();

    Number getCurrentEmployeeId();

    Connection getCurrentDBConnection();

    Double getActualTransferAmount(Number subcntrId, String documentNumber,
                                   String type);

    String generateBMDocumentNumber(String param, String param2);

    List<String> callStoreProcedure(String param, List param2, int param3);

    Number getInvalidTransferStatus(int subcntrId);

    void updateHeaderStatus(String documentNumber, String bmDocumentId,
                            String bmDocumentType, String status);

    String updateTransferHeaderStatus(String documentNumer, String status);
}
